# Trackable Web App - Cloud Build Configuration
#
# This app is deployed to Google Cloud Run via Cloud Build triggers.
#
# Setup Instructions:
# 1. Create a Cloud Build trigger in GCP Console watching the `main` branch
# 2. Configure the trigger to use this file (cloudbuild.yaml)
# 3. Add the following substitution variables in the trigger settings:
#    - _NEXT_PUBLIC_SUPABASE_URL: Your Supabase project URL
#    - _NEXT_PUBLIC_SUPABASE_ANON_KEY: Your Supabase anon/public key
#    - _SERVICE_NAME: Cloud Run service name (e.g., trackable-webapp)
#    - _DEPLOY_REGION: Deployment region (e.g., us-central1)
#
# Runtime Environment Variables:
# These must be set in Cloud Run service configuration (not here):
#    - GOOGLE_GENERATIVE_AI_API_KEY: Gemini API key
#    - GOOGLE_CLIENT_ID: OAuth client ID
#    - GOOGLE_CLIENT_SECRET: OAuth client secret
#    - TRACKABLE_API_URL: Backend API URL (https://api.usetrackable.ai)
#    - GMAIL_PUBSUB_TOPIC: Pub/Sub topic for Gmail push notifications
#    - WEBHOOK_SECRET: Secret for validating Pub/Sub webhooks
#
# Note: NEXT_PUBLIC_* variables are embedded at build time and visible in
# the client bundle. Other env vars are only available server-side at runtime.

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build and deploy to Cloud Run using source deploy (no Dockerfile needed)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--source=.'
      - '--region=${_DEPLOY_REGION}'
      - '--set-build-env-vars=NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL},NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
